version: '3.7'
services:
  api:
    image: tw4204/fastapi-boilerplate
    ports:
      - $APP_PORT:$APP_PORT
    working_dir: '/source'
    volumes:
      - $PWD/source:/source
    command: [
      'uvicorn', 'app:app',
      '--host', '0.0.0.0',
      '--port', $APP_PORT,
    ]
