version: '3.7'
services:
  api:
    image: tw4204/fastapi-boilerplate
    ports:
      - $APP_PORT:$APP_PORT
    working_dir: '/source'
    volumes:
      - $PWD/source:/source
    command: [
      'uvicorn', 'app:app',
      '--host', '0.0.0.0',
      '--port', $APP_PORT,
    ]
  postgres:
    image: postgres:12.1
    volumes:
      - $PWD/volumes/db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=$DATABASE_USER
      - POSTGRES_PASSWORD=$DATABASE_PASS
      - POSTGRES_DB=$DATABASE_NAME

